apiVersion: v1
kind: Secret
metadata:
  name: buildkit
  namespace: gatakko-builder
type: Opaque
stringData:
  config.json: |
    {
      "auths": {
        "registry.gatakko-core.svc.cluster.local:5000": {
          "auth": "YWRtaW46aG9nZXJlZ2NyZWQ="
        }
      }
    }
