apiVersion: v1
kind: Secret
metadata:
  name: ldap
  namespace: gatakko-core
type: Opaque
stringData:
  ldap.crt: |
    -----BEGIN CERTIFICATE-----
    MIIB/jCCAaSgAwIBAgIUSJjvsueapoj47bwnzzriLXZENTkwCgYIKoZIzj0EAwIw
    GzEZMBcGA1UEAwwQQ2x1c3RlciBMb2NhbCBDQTAgFw0yNTAxMDEwMDAwMDBaGA8y
    MTI1MDEwMTAwMDAwMFowLjEsMCoGA1UEAwwjbGRhcC5nYXRha2tvLWNvcmUuc3Zj
    LmNsdXN0ZXIubG9jYWwwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAS7q9D9IWVo
    gTrODR1cXIZ70LwJlZQOsPhHZliWh+gBgQvr0jRcTAhYqAy6tRiJE1V8/9MOhTe2
    OrqCODlhFzQ4o4GwMIGtMB0GA1UdDgQWBBTvdvBm/cAdQFf+UtUoLKhhf3rT9zAf
    BgNVHSMEGDAWgBTLV4EgggXtVgDzsQuA/IGCNGQHyTAOBgNVHQ8BAf8EBAMCBaAw
    DAYDVR0TAQH/BAIwADAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwLgYD
    VR0RBCcwJYIjbGRhcC5nYXRha2tvLWNvcmUuc3ZjLmNsdXN0ZXIubG9jYWwwCgYI
    KoZIzj0EAwIDSAAwRQIhAOd8srglRSf6VLzt+qWcJP3ktEdcUdtpOLyBT+4QwfmL
    AiBTsgTBzhZYDUAFT5mSgxAvsiUfMN0VPVEPBxaqpDQbHA==
    -----END CERTIFICATE-----
  ldap.key: |
    -----BEGIN PRIVATE KEY-----
    MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgUI5PGPiJ/vGujgoy
    j/TNALV0DgGRTfRlukEBw+wHA7qhRANCAAS7q9D9IWVogTrODR1cXIZ70LwJlZQO
    sPhHZliWh+gBgQvr0jRcTAhYqAy6tRiJE1V8/9MOhTe2OrqCODlhFzQ4
    -----END PRIVATE KEY-----
