apiVersion: v1
kind: ConfigMap
metadata:
  name: ldap-init
  namespace: gatakko-core
data:
  10-tls: |
    #!/bin/bash
    set -euC
    [[ $(whoami) = openldap ]] || exec su openldap -s "$0"

    /usr/sbin/slapmodify -b cn=config <<END
    dn: cn=config
    changetype: modify
    replace: olcTLSCertificateKeyFile
    olcTLSCertificateKeyFile: /secret/ldap.key
    -
    replace: olcTLSCertificateFile
    olcTLSCertificateFile: /secret/ldap.crt
    -
    replace: olcTLSCACertificateFile
    olcTLSCACertificateFile: /cacert/ca.crt

    dn: olcDatabase={1}mdb,cn=config
    changetype: modify
    replace: olcSecurity
    olcSecurity: tls=1
    END

  20-access: |
    #!/bin/bash
    set -euC
    [[ $(whoami) = openldap ]] || exec su openldap -s "$0"

    /usr/sbin/slapmodify -b cn=config <<END
    dn: olcDatabase={1}mdb,cn=config
    changetype: modify
    delete: olcAccess
    -
    add: olcAccess
    olcAccess:
     to attrs=userPassword,shadowLastChange,loginShell
      by dn="$LDAP_SSS_DN" write
      by self write
      by anonymous auth
    olcAccess:
     to attrs=entry,objectClass,cn,uid,uidNumber,gidNumber,gecos,
     homeDirectory,memberUid
      by dn="$LDAP_SSS_DN" read
      by self read
    olcAccess:
     to *
      by self read
    END

  30-admin: |
    #!/bin/bash
    set -euC
    [[ $(whoami) = openldap ]] || exec su openldap -s "$0"

    PASSWORD=$(slappasswd -s "$LDAP_ADMIN_PASSWORD")
    /usr/sbin/slapmodify -b cn=config <<END
    dn: olcDatabase={1}mdb,cn=config
    changetype: modify
    replace: olcRootPW
    olcRootPW: $PASSWORD
    END

  40-sss: |
    #!/bin/bash
    set -euC
    [[ $(whoami) = openldap ]] || exec su openldap -s "$0"

    [[ -n $(slapcat -b "$LDAP_BASE_DN" -a "(entryDN=$LDAP_SSS_DN)") ]] \
    || /usr/sbin/slapadd -b "$LDAP_BASE_DN" <<END
    dn: $LDAP_SSS_DN
    objectClass: person
    cn: sss
    sn: sss
    END

    PASSWORD=$(slappasswd -s "$LDAP_SSS_DN_PASSWORD")
    /usr/sbin/slapmodify -b "$LDAP_BASE_DN" <<END
    dn: $LDAP_SSS_DN
    changetype: modify
    replace: userPassword
    userPassword: $PASSWORD
    END
