apiVersion: v1
kind: Secret
metadata:
  name: phpldapadmin
  namespace: gatakko-core
type: Opaque
stringData:
  phpldapadmin.crt: |
    -----BEGIN CERTIFICATE-----
    MIICDzCCAbSgAwIBAgIUHZaXzYJGSju1/DAQuD448VLUW+cwCgYIKoZIzj0EAwIw
    GzEZMBcGA1UEAwwQQ2x1c3RlciBMb2NhbCBDQTAgFw0yNTAxMDEwMDAwMDBaGA8y
    MTI1MDEwMTAwMDAwMFowNjE0MDIGA1UEAwwrcGhwbGRhcGFkbWluLmdhdGFra28t
    Y29yZS5zdmMuY2x1c3Rlci5sb2NhbDBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IA
    BE4HsgBFC6eqv7O5u+KJOiYhDRvF06/+clOMTZhXtGu46NjO6chwOSDyBXbjedoi
    8Lf9m1odcnkYp6pVYK1NX9mjgbgwgbUwHQYDVR0OBBYEFOqTH3zswh6iLZ93LEMo
    3drMrwUrMB8GA1UdIwQYMBaAFMtXgSCCBe1WAPOxC4D8gYI0ZAfJMA4GA1UdDwEB
    /wQEAwIFoDAMBgNVHRMBAf8EAjAAMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEF
    BQcDAjA2BgNVHREELzAtgitwaHBsZGFwYWRtaW4uZ2F0YWtrby1jb3JlLnN2Yy5j
    bHVzdGVyLmxvY2FsMAoGCCqGSM49BAMCA0kAMEYCIQC22kRRw1P+R1DfdE6j7moh
    2AIesQgTYOoHL6/emOYCSwIhAPMAIPkpy6KMneyFN9a31Be4Vr/DEdz5qYA6P1Y/
    7WxG
    -----END CERTIFICATE-----
  phpldapadmin.key: |
    -----BEGIN PRIVATE KEY-----
    MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgPJK9v8Qpau+xda/k
    VW+4UPD+4R4888mopmp3JLqHFR+hRANCAAROB7IARQunqr+zubviiTomIQ0bxdOv
    /nJTjE2YV7RruOjYzunIcDkg8gV243naIvC3/ZtaHXJ5GKeqVWCtTV/Z
    -----END PRIVATE KEY-----
