apiVersion: v1
kind: Secret
metadata:
  name: registry
  namespace: gatakko-core
type: Opaque
stringData:
  registry.crt: |
    -----BEGIN CERTIFICATE-----
    MIICBzCCAaygAwIBAgIUS/iunhyr+rC/J7L+Au9Xg3YyojowCgYIKoZIzj0EAwIw
    GzEZMBcGA1UEAwwQQ2x1c3RlciBMb2NhbCBDQTAgFw0yNTAxMDEwMDAwMDBaGA8y
    MTI1MDEwMTAwMDAwMFowMjEwMC4GA1UEAwwncmVnaXN0cnkuZ2F0YWtrby1jb3Jl
    LnN2Yy5jbHVzdGVyLmxvY2FsMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAErImQ
    C3Hv+4j7IwdV61p/PMQ4Tb+7qCt3sLJ5ZUMbKug0ZX9YiNUV/Gc4vQ83Owr1sARB
    FTmQo4j0nmWGzAzfOKOBtDCBsTAdBgNVHQ4EFgQURp8Z/2p0kkZ7Hi19qrSJyZ3q
    6TMwHwYDVR0jBBgwFoAUy1eBIIIF7VYA87ELgPyBgjRkB8kwDgYDVR0PAQH/BAQD
    AgWgMAwGA1UdEwEB/wQCMAAwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMC
    MDIGA1UdEQQrMCmCJ3JlZ2lzdHJ5LmdhdGFra28tY29yZS5zdmMuY2x1c3Rlci5s
    b2NhbDAKBggqhkjOPQQDAgNJADBGAiEAud9TZCOrfE0spgviqJqOAgQNYUIU/Jyt
    hxYfKCgW/jICIQCjkPzFGFo8Cd2MX24oObtbcRtOv1ZpeDpR07YNIAAYYw==
    -----END CERTIFICATE-----
  registry.key: |
    -----BEGIN PRIVATE KEY-----
    MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQglW4RvTp0fHNemu5u
    MY11RJ467uQVFkwp1usxBU2Cm5+hRANCAASsiZALce/7iPsjB1XrWn88xDhNv7uo
    K3ewsnllQxsq6DRlf1iI1RX8Zzi9Dzc7CvWwBEEVOZCjiPSeZYbMDN84
    -----END PRIVATE KEY-----
  htpasswd: |
    admin:$2y$05$SqvENiXyMO43PBGIK4kXwuf6KJKgtm43gqEouAY1dB82b9JtmmEpS
