apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
  namespace: gatakko-core
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
      - name: registry
        image: registry:3
        ports:
        - containerPort: 5000
          protocol: TCP
        env:
        - name: REGISTRY_AUTH
          value: htpasswd
        - name: REGISTRY_AUTH_HTPASSWD_REALM
          value: cluster.local
        - name: REGISTRY_AUTH_HTPASSWD_PATH
          value: /secret/htpasswd
        - name: REGISTRY_HTTP_TLS_CERTIFICATE
          value: /secret/registry.crt
        - name: REGISTRY_HTTP_TLS_KEY
          value: /secret/registry.key
        volumeMounts:
        - mountPath: /var/lib/registry
          name: registry-pvc
        - mountPath: /secret
          name: registry-secret
      volumes:
      - name: registry-pvc
        persistentVolumeClaim:
          claimName: registry
      - name: registry-secret
        secret:
          secretName: registry
