apiVersion: v1
kind: Secret
metadata:
  name: webui
  namespace: gatakko-core
type: Opaque
stringData:
  webui.crt: |
    -----BEGIN CERTIFICATE-----
    MIICATCCAaagAwIBAgIUEdv/wgZhLsJkR+4cJ/PzrxWnX8IwCgYIKoZIzj0EAwIw
    GzEZMBcGA1UEAwwQQ2x1c3RlciBMb2NhbCBDQTAgFw0yNTAxMDEwMDAwMDBaGA8y
    MTI1MDEwMTAwMDAwMFowLzEtMCsGA1UEAwwkd2VidWkuZ2F0YWtrby1jb3JlLnN2
    Yy5jbHVzdGVyLmxvY2FsMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEsamwJ+Od
    4UbS+00oca3KjByO0LCnd7UDSC3fLtBeLblR09PVMeMlcPFbBpEbz7iJ8ko+rBtO
    Md7d5Mjr/KsUAaOBsTCBrjAdBgNVHQ4EFgQUoYAmicDJmtZlE6yUoSGT6RkNopow
    HwYDVR0jBBgwFoAUy1eBIIIF7VYA87ELgPyBgjRkB8kwDgYDVR0PAQH/BAQDAgWg
    MAwGA1UdEwEB/wQCMAAwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMC8G
    A1UdEQQoMCaCJHdlYnVpLmdhdGFra28tY29yZS5zdmMuY2x1c3Rlci5sb2NhbDAK
    BggqhkjOPQQDAgNJADBGAiEAwdJSEKGRep7eHKdwuq+7syAeU9KtPHsbnKIQQj8t
    C3ECIQDN/Xm6o+DwnysGQh1jhF89pUx+3xMMi2lgXoD0bGipaQ==
    -----END CERTIFICATE-----
  webui.key: |
    -----BEGIN PRIVATE KEY-----
    MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgYNCsj+JyyfaLZAPl
    T8bkaBu7Iv66+DE+yjaFJdrlPIahRANCAASxqbAn453hRtL7TShxrcqMHI7QsKd3
    tQNILd8u0F4tuVHT09Ux4yVw8VsGkRvPuInySj6sG04x3t3kyOv8qxQB
    -----END PRIVATE KEY-----
