apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: haproxy
  namespace: gatakko-core
spec:
  selector:
    matchLabels:
      app: haproxy
  template:
    metadata:
      labels:
        app: haproxy
    spec:
      containers:
      - name: haproxy
        image: docker.io/haproxy:lts
        volumeMounts:
        - mountPath: /usr/local/etc/haproxy/haproxy.cfg
          name: haproxy-config
          subPath: haproxy.cfg
      volumes:
      - name: haproxy-config
        configMap:
          name: haproxy
          items:
          - key: haproxy.cfg
            path: haproxy.cfg
