apiVersion: v1
kind: Secret
metadata:
  name: tls
  namespace: gatakko-user
type: Opaque
stringData:
  server.crt: |
    -----BEGIN CERTIFICATE-----
    MIIBwzCCAWmgAwIBAgIUCQ77qD4ATtgylkDWxdqRuEANwNMwCgYIKoZIzj0EAwIw
    FDESMBAGA1UEAwwJbG9jYWxob3N0MCAXDTI1MDEwMTAwMDAwMFoYDzIxMjUwMTAx
    MDAwMDAwWjAUMRIwEAYDVQQDDAlsb2NhbGhvc3QwWTATBgcqhkjOPQIBBggqhkjO
    PQMBBwNCAASk1mtCfhmpviV8HrAN492z7Gz37Fheywax2VHTtI5oZyFJUmdll8ma
    rwACVhxWe2AWo450e6MwKzBcZYWzUaPio4GWMIGTMB0GA1UdDgQWBBSH4//Jg1DL
    79EJ9F8FpZVjHEAdWjAfBgNVHSMEGDAWgBSH4//Jg1DL79EJ9F8FpZVjHEAdWjAO
    BgNVHQ8BAf8EBAMCBaAwDAYDVR0TAQH/BAIwADAdBgNVHSUEFjAUBggrBgEFBQcD
    AQYIKwYBBQUHAwIwFAYDVR0RBA0wC4IJbG9jYWxob3N0MAoGCCqGSM49BAMCA0gA
    MEUCIQDexCA6bLL+OmW1qYCjtJrg2bjD1oXMCSwkyO5nznIvlgIgefDeQgfjybyY
    uIkPXozZCP3UESJG2RAg9BtcxMkXUXE=
    -----END CERTIFICATE-----
  server.key: |
    -----BEGIN PRIVATE KEY-----
    MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgbSD/99hEKuX8AsC1
    /w0IsqDZzj3tQnLEcfS0nwVZ986hRANCAASk1mtCfhmpviV8HrAN492z7Gz37Fhe
    ywax2VHTtI5oZyFJUmdll8marwACVhxWe2AWo450e6MwKzBcZYWzUaPi
    -----END PRIVATE KEY-----
